version: '3'
services:
  redis:
    image: redis:alpine
  backend:
    image: '111'
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    environment:
      - REDIS=redis
  frontend:
    image: '110'
    ports:
      - 5000:5000
